### ISSUE TITLE
Managing the EBCDIC codepage of the downloaded file

### ISSUE THREAD

**Issue by FALLAI-Denis** [NEORIS-ZDEVOPS/DS-Editor#4]
Hi,

When viewing the raw format of the downloaded file, it appears in EBCDIC, so the file is probably downloaded in binary format, without conversion, from the z/OS system.

When viewing the file in "display" mode, there is a conversion or interpretation from EBCDIC to UTF-8 (? since VS Code works mainly in UTF-8), but the codepage used on the z/OS system is not taken into account, and therefore accented characters are poorly rendered.

For example, we use the IBM-1147 (French) encoding on our z/OS system, (configured in our 3270 emulator and in the Zowe z/OSMF profiles), but it seems that the translation is done either with an IBM-037 (US) encoding, or with an IBM-1047 (USS) encoding.

We did not find an option to declare the EBCDIC encoding used to render the file at the consultation/update GUI level.

![image](https://github.com/user-attachments/assets/7685d755-0f8d-4878-b075-612cff35a2ec)

![image](https://github.com/user-attachments/assets/d206930d-900c-4109-bb84-2492a2459274)

![image](https://github.com/user-attachments/assets/d184d36f-e206-4b71-8427-f856cd7245c9)

![image](https://github.com/user-attachments/assets/1295b0d6-8752-4b74-bd2a-5a5bbbe7bd92)

Downloaded with native Zowe Explorer:

![image](https://github.com/user-attachments/assets/30d75974-43cb-43f0-8701-35554b12304a)

Thanks.

**Comment by antonkc** [comment]
Greetings @FALLAI-Denis ,

You can expect the capability to change the working code page between preset codepages in the next release. Including ebcdic 1147.

We don't have a release date yet, but it will be relatively soon.

**Comment by antonkc** [comment]
Greetings @FALLAI-Denis ,

We just released version 2.2.0. This one includes codec selection.

Please, check if it fixes your problem.

**Comment by FALLAI-Denis** [comment]
Hi @antonkc,

It seems that there is a problem.
Is the extension compatible with Zowe Explorer 3.x.x?

![image](https://github.com/user-attachments/assets/78a7d789-4b2b-4272-8ac0-ad548a647088)

Zowe Profile and API management has changed between Zowe Explorer 2.x.x and Zowe Explorer 3.x.x.

Note that we use Zowe project profiles, via zowe.config.json / zowe.schema.json files at the root of the VS Code workspace, but the problem is the same with a user profile..

Thanks.

**Comment by FALLAI-Denis** [comment]
PS: 

See if the problem could not be related to the incident:
* #5 

```
2024-11-08 20:37:58.551 [error] The document doesn't exists: Error: The document doesn't exists
	at t.create (c:\Users\S0070188\.vscodeMainframe\neoris.dseditor-2.2.0\dist\extension.js:1196:4109)
	at async Ote.openCustomDocument (c:\Users\S0070188\.vscodeMainframe\neoris.dseditor-2.2.0\dist\extension.js:1200:12453)
	at async iH.$createCustomDocument (file:///c:/ProgramData/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:93895)
2024-11-08 20:37:58.552 [error] Error: The document doesn't exists
	at t.create (c:\Users\S0070188\.vscodeMainframe\neoris.dseditor-2.2.0\dist\extension.js:1196:4109)
	at async Ote.openCustomDocument (c:\Users\S0070188\.vscodeMainframe\neoris.dseditor-2.2.0\dist\extension.js:1200:12453)
	at async iH.$createCustomDocument (file:///c:/ProgramData/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:93895)
2024-11-08 20:40:55.980 [error] The document doesn't exists: Error: The document doesn't exists
	at t.create (c:\Users\S0070188\.vscodeMainframe\neoris.dseditor-2.2.0\dist\extension.js:1196:4109)
	at async Ote.openCustomDocument (c:\Users\S0070188\.vscodeMainframe\neoris.dseditor-2.2.0\dist\extension.js:1200:12453)
	at async iH.$createCustomDocument (file:///c:/ProgramData/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:93895)
2024-11-08 20:40:55.980 [error] Error: The document doesn't exists
	at t.create (c:\Users\S0070188\.vscodeMainframe\neoris.dseditor-2.2.0\dist\extension.js:1196:4109)
	at async Ote.openCustomDocument (c:\Users\S0070188\.vscodeMainframe\neoris.dseditor-2.2.0\dist\extension.js:1200:12453)
	at async iH.$createCustomDocument (file:///c:/ProgramData/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:93895)
```

But the file is not downloaded (missing from the temp folder), even in the .vscode folder. So the problem must be with the download and use of the Zowe profile.

**Comment by FALLAI-Denis** [comment]
Hi,

Please note that after "correcting" the z/OSMF profile (adding the "protocol" property in the profile), the MVS file is now downloaded correctly. 
However, the EBCDIC encoding indicated in the z/OSMF profile is still not taken into account.

See:
* #5 

Also note that not all files are necessarily encoded with the default codepage defined on the z/OSMF profile. Our default codepage is IBM-1147, (France Euro), but we are increasingly using files encoded in IBM-1047, IBM-1208/UTF8 or ISO-8859-x.
It would also be necessary to be able to specify the encoding to use to interpret the data in the downloaded file.
As the download is apparently done in binary mode, the interpretation of the codepage comes next: the DS Editor consultation/editing interface could offer to enter or select the codepage to use, or even to change it during consultation/editing.

Thanks.

**Comment by antonkc** [comment]
Greetings @FALLAI-Denis ,

Please, to change the codec, use the command "Change z/OS File Editor codec".

The profile is not taken into account to select a codec.

**Comment by antonkc** [comment]
I will be closing this issue. Take into account that the codec can be selected per document and per vscode configuration basis. 
![image](https://github.com/user-attachments/assets/4f9cbcd8-9f83-4edc-86cf-7741e98f8444)
![image](https://github.com/user-attachments/assets/ceeb7587-47cc-4f9c-95b4-76b56c02b6e2)


I created a new one for making the setting track the codec configured in the zowe profile in #6
